#Ques: A central power plant, rated at 800,000 kW, generates steam at 585 K and discards heat to a river at 295 K. If the thermal efficiency of the plant is 70% of the maximum possible value, how much heat is discarded to the river at rated power?
power= int(input("Enter the power generated by the power plant in kW\n"))
Th=int(input("Enter the temperature of power plant in Kelvin\n"))
Tc=int(input("Enter the temperature of the river in Kelvin\n"))
te=int(input("Enter the thermal efficiency of the power plant in percentage\n"))
print("\nThe actual thermal efficiency is given by:\nη = (1 - Temperature of river/Temperature of power plant) X thermal efficieny")
print("η = (1 - Tc/Th) X te")
n=(1 - Tc/Th)*te/100
print("η =", n)
print("Using 1st Law:")
print("ΔU = Q + W\nΔU = 0 and Q = Qh + Qc\nTherefore,\nW = −Qh − Qc\nQc = (1−η/η) X W")
Qc=((1-n)/n)*power
print("Qc =", Qc,"kW")
